site_name: My first robot
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Learning Journals:
      - Learning Journal - Joshua: Learning Journals/learning-journal-joshua.md
      - Learning Journal - Tim: Learning Journals/learning-journal-tim.md
      - Learning Journal - Tom: Learning Journals/learning-journal-tom.md
      - Learning Journal - Despoina: Learning Journals/learning-journal-despoina.md
      - Learning Journal - Elizaveta: Learning Journals/learning-journal-elizaveta.md
      - Learning Journal - Xander: Learning Journals/learning-journal-xander.md
  - Meetings:
      - Gerald:
          - 13 November: Meetings/Gerald/13-11-2024.md
          - 20 November: Meetings/Gerald/20-11-2024.md
      - Bernardo:
          - 22 November: Meetings/Bernardo/22-11-2024.md
  - Setup:
      - Server: Setup/server.md
      - ZeroTier: Setup/zerotier.md
  - Embedded:
      - Code: 
          - Movement: Embedded/Code/movement.md
  - Database: database.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra_style.css