site_name: My First Robot
theme:
  name: material
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: teal

nav:
  - 🏠 Home: index.md
  - Device: 
    - 🔨 Setup:
      - Server: Setup/server.md
      - ZeroTier: Setup/zerotier.md
    - ⌨ Code: 
      - Movement: Embedded/Code/movement.md
    - 💾 Database: database.md
  
  - Process:
    - 📃 Conventions:
        - C++: Learning Journals/learning-journal-joshua.md
        - HTML: Learning Journals/learning-journal-tim.md
        - CSS: Learning Journals/learning-journal-tom.md
        - JavaScript: Learning Journals/learning-journal-tom.md
    - 🔍 Learning Journals:
        - Joshua Ganga: Learning Journals/learning-journal-joshua.md
        - Tim van Dantzig: Learning Journals/learning-journal-tim.md
        - Tom Jonker: Learning Journals/learning-journal-tom.md
        - Despoina Sfantou: Learning Journals/learning-journal-despoina.md
        - Elizaveta Sabanova: Learning Journals/learning-journal-elizaveta.md
        - Xander Tamis: Learning Journals/learning-journal-xander.md
    - 📞 Meetings:
        - Gerald:
            - Nov 13, 2024: Meetings/Gerald/13-11-2024.md
            - Nov 20, 2024: Meetings/Gerald/20-11-2024.md
        - Bernardo:
            - Nov 22, 2024: Meetings/Bernardo/22-11-2024.mdflop
  


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra_style.css