<<<<<<< HEAD
image: python:3.9
=======
image: python:3.9-slim

before_script:
  - time apt update
  - time pip install -r requirements.txt
  - time cd mdocotion && python setup.py install && cd ..
>>>>>>> new-remote/main

pages:
  stage: deploy
  tags:
    - hva
  script:
<<<<<<< HEAD
    - pip install mkdocs-material
    - mkdocs build -d public
  artifacts:
    paths:
      - public
  only:
    - main
=======
    - time mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  GIT_SUBMODULE_STRATEGY: recursive
>>>>>>> new-remote/main
