| Requirement                     |Tribot|Robot dog|Classic|
|---------------------------------|------|---------|-------|
|Wow-factor (moving parts)        |It has a front wheel on a servo, we don't yet know if it has precise enough movement.|Yes, it has moving legs which allows it to do lots of things (walking, sitting/lying down, other tricks). The legs are on servos so they can move very precisely.|It only has 2 wheels, so it's not very special. It can move very precise however.|
|Easy to (dis)assemble            |Depending on how complicated our design will be and how we will mount the motor, wheels and servo, it will be easy to assemble and dissasemble.|A bit more difficult to assemble. The servos and legs need to be in specific orientations to make the animation work. Unlike the other 2, it's not a plate with things mounted on the top/bottom but more like a box.|The simplest of all 3 to assemble|
|Can handle repeated (dis)assembly|This will also depend on our design, especially on the motor assembly. The rest is just a plate (as of now) so it will be strong enough.|Also depends on our design. Our current design is not strong enough for this, but it can be changed.|Because it is so simple, it can be assembled and dissasembled over and over|
|Total price of robot is below €20|Yes, the robot is pretty simple so it's cheap.|It will still fit in the budget, but barely. It has 4 servos and servos are expensive. This limits the choice of microcontrollers and sensors we can add.|Very cheap because it's so simple|
|Max movement speed of 2km/h      |It's driven by a DC-motor, so we can adjust the speed to 2km/h.|Depends on the walking animation, but in our testing so far it is not very fast so fits the requirement.|As of now it's driven by stepper motors, so we can adjust the speed to 2 km/h|
|Usable on open day               |Yes, it's a simple robot that students can assemble and drive themselves.|It's a bit more complicated but still usable|It's very simple so everyone can assemble and drive it|
|Usable in studios                |Depends on what we add, if it has no sensors it will be too simple|Yes, it is a bit more complex but still universal (you can add things)|Depends on what we add, but because of the wheel setup it can move in any direction with a lot of precision|
|Attracts our target audience     |Don't know yet|Don't know yet, but when we testes it here everyone in class was watching.|Don't know yet, but it is already used in 1st year education|
|Bill of materials                |As of now it has 1 DC motor, 1 servo, 1 microcontroller and a battery. The rest is lasercut wood so the BOM is very small.|It has 4 servos so it's more expensive, along with the same microcontroller and battery|It only has 2 stepper motors, along with the battery and controller. That makes the BOM very small|